### ISSUE TITLE
Strange behavior with incorrect user input 

### ISSUE THREAD

**Issue by LSoderquist** [amscott0/AbrahamS_IsaacS_FinalProject#2]
When changing difficulty, if the user enters multiple words, the program enters an infinite loop of printing the menu. When inputting a move, if the user inputs any non-number characters (other than spaces), the program enters the same infinite loop of printing the menu. When inputting a move, if a user enters more than 2 integers (ex. input of "1 1 1" or "1 1 1 1"), menu can sometimes print multiple times, and the user can sometimes be asked again to enter a column and row. Additionally, if the user enters an invalid column or row (ex. "4 1") when inputting their move, the invalid number is interpreted as the input modulus 3 instead of telling the user their input is invalid (ex. When the user inputs "4 4" an X is placed in the "1 1" space).

**Comment by amscott0** [comment]
Fixed. I put the if statements in the wrong order, I first should have checked if the input was invalid, then all other checks. I also made a nifty do-while loop to make sure the user input is not a string or something that would make an infinite loop in my inputMove().
